### ISSUE TITLE
EventStore StreamProvider?

### ISSUE THREAD

**Issue by normanhh3** [OrleansContrib/orleans.eventsourcing#1]
Was looking into EventStore and then came across Orleans, looks like it could be a nice match and it appears you have made some great progress with this repo.

Have you investigated at all supporting Orleans streaming on EventStore by chance?

**Comment by jkonecki** [comment]
Hi. Support for Event Sourcing has been integrated into the main Orleans repo but hasn't been released yet. It contains extensibility point in a form of a provider. Once it's released this report will become obsolete and you will be able to create a provider for your favourite event store. I plan to create one for GetEventStore and Streamstone.

**Comment by normanhh3** [comment]
Very cool.  Glad to hear it.
